wandb_version: 1

DATASET_PATH:
  desc: null
  value: C:/Users/Platz3/PycharmProjects/Segmentation Network/venv/Network/Dataset/Dataset
    1/WannerFIB/
DEVICE:
  desc: null
  value: cpu
PIN_MEMORY:
  desc: null
  value: true
NUM_CLASSES:
  desc: null
  value: 3
INIT_LR:
  desc: null
  value: 0.001
NUM_EPOCHS:
  desc: null
  value: 40
BATCH_SIZE:
  desc: null
  value: 64
INPUT_IMAGE_WIDTH:
  desc: null
  value: 128
INPUT_IMAGE_HEIGHT:
  desc: null
  value: 128
THRESHOLD:
  desc: null
  value: 0.5
BASE_OUTPUT:
  desc: null
  value: output
PATIENCE:
  desc: null
  value: 5
MIN_NUM_EPOCHS:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700862623.041109
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
